### ISSUE TITLE
TO FIX: Micro ACL Bugs

### ISSUE THREAD

**Issue by ChrisKSeal** [UoA-eResearch/mytardis#165]
- [x] Download+edit buttons on list view - tie to individual files via ajax_pages
- [x] Download+edit buttons on tree view
- [x] Experiment-Download All button bypassing MicroACLs
- [x] remove iiif image preview if not any Download access
- [x] Image preview for tiles needs to respect Micro
- [x] Image preview for tiles not working (Macro+Micro)
- [x] Owner ACL canDownload+canSensitive should not be set to False by default

**Comment by mike-ivs** [comment]
- [x] Owner ACL canDownload+canSensitive should not be set to False by default

Texted and fixed in commit 3f87c8ac4cbecc2f3e7eee78117197e90910f3bd
